{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Generated by `nixos-generate-config` on target machine
  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "nvme" "usbhid"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
