{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Generated by `nixos-generate-config` on target machine
  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "nvme" "usbhid"];
      kernelModules = [];
    };
    kernelModules = [];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
